spring.application.name=urlshortener

spring.data.mongo.authentication-database=admin
spring.data.mongo.auto-index-creation=true
spring.data.mongo.host=localhost
spring.data.mongo.port=27017
spring.data.mongo.database=shortenerdb
spring.data.mongo.username=admin
spring.data.mongo.password=123